# Generated by Django 4.1.4 on 2023-04-02 18:41

import board_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[], default='general', max_length=100, verbose_name=board_app.models.Category),
        ),
    ]
