# Generated by Django 4.1.4 on 2023-03-15 15:56

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
