# Generated by Django 4.1.4 on 2023-04-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_post_image_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
    ]
