# Generated by Django 4.1.4 on 2023-03-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
