# Generated by Django 4.1.4 on 2023-03-22 19:06

import board_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Ubuntu', 'Ubuntu'), ('Nextjs', 'Nextjs'), ('Blender', 'Blender'), ('Tailwind CSS', 'Tailwind CSS')], default='general', max_length=100, verbose_name=board_app.models.Category),
        ),
    ]
