# Generated by Django 4.1.4 on 2023-03-24 15:19

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0015_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
